update

diff --git a/.github/workflows/nightly-adv-logger.yml b/.github/workflows/nightly-adv-logger.yml
--- a/.github/workflows/nightly-adv-logger.yml
+++ b/.github/workflows/nightly-adv-logger.yml
@@ -161,10 +161,13 @@ jobs:
             exit 1
           fi
 
-          [ "$found_pei"   -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [PEI  ]"; failed=1; }
           [ "$found_dxe"   -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [DXE  ]"; failed=1; }
-          [ "$found_mcore" -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [MCORE]"; failed=1; }
           [ "$found_rtdxe" -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [RTDXE]"; failed=1; }
+
+          if [ "${{ matrix.platform }}" -eq "Q35"]
+            [ "$found_pei"   -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [PEI  ]"; failed=1; }
+            [ "$found_mcore" -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [MCORE]"; failed=1; }
+          fi
 
           if [ "$failed" -ne 0 ]; then
             exit 1
