update

diff --git a/.github/workflows/nightly-adv-logger.yml b/.github/workflows/nightly-adv-logger.yml
--- a/.github/workflows/nightly-adv-logger.yml
+++ b/.github/workflows/nightly-adv-logger.yml
@@ -125,6 +125,8 @@ jobs:
             exit 1
           fi
 
+          cp ${{ env.LOG_FILE }} ${{ steps.build-platform.outputs.log-path }}
+
           found_pei=0
           found_dxe=0
           found_mcore=0
@@ -162,12 +164,12 @@ jobs:
             exit 1
           fi
 
-          [ "$found_dxe"   -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [DXE  ]"; failed=1; }
-          [ "$found_rtdxe" -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [RTDXE]"; failed=1; }
+          [ "$found_dxe"   -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing log tagged [DXE  ]"; failed=1; }
+          [ "$found_rtdxe" -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing log tagged [RTDXE]"; failed=1; }
 
           if [ "${{ matrix.platform }}" = "Q35" ]; then
-            [ "$found_pei"   -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [PEI  ]"; failed=1; }
-            [ "$found_mcore" -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing tag [MCORE]"; failed=1; }
+            [ "$found_pei"   -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing log tagged [PEI  ]"; failed=1; }
+            [ "$found_mcore" -eq 1 ] || { echo "::error file=${LOG_FILE}::Missing log tagged [MCORE]"; failed=1; }
           fi
 
           if [ "$failed" -ne 0 ]; then
