update

diff --git a/.github/workflows/nightly-adv-logger.yml b/.github/workflows/nightly-adv-logger.yml
--- a/.github/workflows/nightly-adv-logger.yml
+++ b/.github/workflows/nightly-adv-logger.yml
@@ -175,9 +175,9 @@ jobs:
             exit 1
           fi
 
-          if ! cmp -n "$(stat -c %s UEFI_LOG1.txt)" UEFI_LOG1.txt ${{ env.LOG_FILE }} >/dev/null 2>&1; then
-            echo "::error::UEFI_LOG1.txt is not the start of ${{env.LOG_FILE}}"
-            cp UEFI_LOG1.txt ${{ steps.build-platform.outputs.log-path }}
+          if ! cmp -n "$(stat -c %s UEFI_Log1.txt)" UEFI_Log1.txt ${{ env.LOG_FILE }} >/dev/null 2>&1; then
+            echo "::error::UEFI_Log1.txt is not the start of ${{env.LOG_FILE}}"
+            cp UEFI_Log1.txt ${{ steps.build-platform.outputs.log-path }}
             exit 1
           fi
 
