update

diff --git a/.github/workflows/nightly-adv-logger.yml b/.github/workflows/nightly-adv-logger.yml
--- a/.github/workflows/nightly-adv-logger.yml
+++ b/.github/workflows/nightly-adv-logger.yml
@@ -175,7 +175,11 @@ jobs:
             exit 1
           fi
 
-          mv ${{ env.LOG_FILE }} ${{ steps.build-platform.outputs.log-path }}
+          if ! cmp -n "$(stat -c %s UEFI_LOG1.txt)" UEFI_LOG1.txt ${{ env.LOG_FILE }} >/dev/null 2>&1; then
+            echo "::error::UEFI_LOG1.txt is not the start of ${{env.LOG_FILE}}"
+            cp UEFI_LOG1.txt ${{ steps.build-platform.outputs.log-path }}
+            exit 1
+          fi
 
       - name: Publish Logs
         if: always()
